### ISSUE TITLE
Different format for regex checks

### ISSUE THREAD

**Issue by mew1033** [HubbleStack/Pulsar#22]
Should we consider using a different format for the regex checks? Instead of each item being a dict with `regex: True` underneath it, would it be better to do something like this?:

```
- /ignore/me
- /me/too
- regex:
  - \/iLoveRegex\./d*$
  - \/regex\/forLife
- potentially/other/files
```

As opposed to what it is now:

```
- /ignore/me
- /me/too
- \/iLoveRegex\./d*$:
    regex: True
- \/regex\/forLife:
    regex: True
- potentially/other/files
```

**Comment by basepi** [comment]
It think we should leave it as is. Although it's more verbose, it's also more salt-y. I don't love the idea of magic keys in dictionaries, especially because this config just isn't going to get all that long or change all that often in the long run.

**Comment by cedwards** [comment]
+1

**Comment by basepi** [comment]
(I closed this assuming Christer was +1-ing my comment, but I could be wrong. In any case, conversation can definitely continue. :) )
