### ISSUE TITLE
minion becomes unresponsive when pulsar returner can't reach splunk

### ISSUE THREAD

**Issue by beelzebob** [HubbleStack/Pulsar#35]
When splunk is unavailable, the pulsar returner hangs the minion (it is not responsive from the master):

[DEBUG   ] LazyLoaded splunk_pulsar_return.returner
[INFO    ] Options: {"index": "target_hubble", "token": "REDACTED", "sourcetype": "hubble_pulsar", "indexer": "REDACTED"}

https://unavailable-splunk-server:8088/services/collector/event
[INFO    ] Starting new HTTPS connection (1): REDACTED

**Comment by basepi** [comment]
Thanks, we'll get this fixed.
