### ISSUE TITLE
add_watch: cannot watch ... WD=-1 Errno=No space left on device (ENOSPC)

### ISSUE THREAD

**Issue by d3xt3r01** [HubbleStack/Pulsar#45]
Even after /var as per https://github.com/HubbleStack/Pulsar/commit/c7f6f70aab8bb762af197b49a1407cdd961dacd6

```
# grep 'No space left' /var/log/salt/minion
2016-10-12 13:14:57,957 [pyinotify                                                ][ERROR   ][pid] add_watch: cannot watch ... WD=-1 Errno=No space left on device (ENOSPC)
...
# tons of these
```

```
# df -h -T
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/sda2      ext4    99G   11G   83G  12% /
tmpfs          tmpfs   16G   16K   16G   1% /dev/shm
/dev/sda1      ext4   190M   92M   88M  52% /boot
/dev/sda6      ext4   952G   22G  883G   3% /var
```

```
# grep -v unlimited /proc/<pid>/limits
Limit                     Soft Limit           Hard Limit           Units
Max processes             32768                32768                processes
Max open files            1024                 4096                 files
Max locked memory         65536                65536                bytes
Max pending signals       128124               128124               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
```

**Comment by basepi** [comment]
So `/var` was no longer in your pulsar config? Did you upgrade to the latest config without `/var`?

If so, I wonder if this is related to #32

**Comment by d3xt3r01** [comment]
Yes, as per that commit, I removed var and restarted the minion.

**Comment by basepi** [comment]
Hmm. I would expect a restart of the minion to purge those old watches. I may have to do some testing.

**Comment by corleyma** [comment]
I believe I am experiencing similar behavior--restarting a minion does not appear to purge the watches.

**Comment by basepi** [comment]
Thanks for verifying.

**Comment by mew1033** [comment]
You can check if you're our of watches by using tail. (See here: http://unix.stackexchange.com/a/13757/171488)
Also check how many allowed watches you have configured.

**Comment by basepi** [comment]
We already fetch the list of watches so we only update the ones that need to be updated. But we don't do a "hey, should this watch be here at all?" check.

**Comment by basepi** [comment]
Turns out this was an issue with `/proc/sys/fs/inotify/max_user_watches`. I've added a troubleshooting section to the readme: https://github.com/HubbleStack/Pulsar#troubleshooting

Closing this.

**Comment by basepi** [comment]
(The issue with lack of watch removal is tracked in https://github.com/HubbleStack/Pulsar/issues/32)
