### ISSUE TITLE
Issue processing regex exclusions?

### ISSUE THREAD

**Issue by corleyma** [HubbleStack/Pulsar#48]
```
[CRITICAL][27869] Beacon processing failed: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 948, in _process_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.6/site-packages/salt/minion.py", line 476, in process_beacons
    return self.beacons.process(b_conf)
  File "/usr/lib/python2.6/site-packages/salt/beacons/__init__.py", line 56, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/var/cache/salt/minion/extmods/beacons/pulsar.py", line 232, in beacon
    if exclude.values()[0].get('regex', False):
AttributeError: 'bool' object has no attribute 'get'
. No beacons will be processed.
```

I could test things more thoroughly, but I'm pretty sure this traceback was generated by the following regex: 

```
/etc:
  exclude:
    - \/etc\/sfx\/service_id[a-zA-Z0-9_]{6}:
        regex: True
```

**Comment by corleyma** [comment]
I'm having issues testing this to confirm that this regex is the culprit.  Theoretically, this module should be reloaded every time the minion is restarted but I don't see the exclusions being registered, etc.

**Comment by basepi** [comment]
Can you throw single quotes around your regex and try again?

```
/etc:
  exclude:
    - '\/etc\/sfx\/service_id[a-zA-Z0-9_]{6}':
        regex: True
```

Also note that you need to do a `cp.cache_file` to get the file down to the minion. The provided schedule only does it once a day. _Then_ restart your minion to pick up the new config.

**Comment by basepi** [comment]
@corleyma Did adding quotes work here?

**Comment by basepi** [comment]
I'm going to assume quotes were the issue. Feel free to comment if that's not the case and I'll re-open.
