### ISSUE TITLE
Files Changed by Salt States Have 6-digit Random alphanumeric appended to path

### ISSUE THREAD

**Issue by corleyma** [HubbleStack/Pulsar#49]
This is the from the returner on two different hosts:

```
...
'change': 'IN_MODIFY',
 'name': 'remove_old_docker_containers_and_imagessDbKBk',
 'path': '/usr/local/bin/remove_old_docker_containers_and_imagessDbKBk',
...
```

and

```
...
'change': 'IN_MODIFY'
 'name': 'remove_old_docker_containers_and_imagessDbKBk',
 'path': '/usr/local/bin/remove_old_docker_containers_and_imagessDbKBk',
...
```

The actual file name does not include these characters.  And, I modify a file manually I don't see this behavior.  Any clue what's going on with that?

**Comment by basepi** [comment]
I wonder if salt is making tempfiles and moving them into place maybe? Not sure, this is definitely odd.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#26
