### ISSUE TITLE
Some events returned to Splunk have a semicolon and random string appended to the file name

### ISSUE THREAD

**Issue by mew1033** [HubbleStack/Pulsar#62]
There are some events getting returned to Splunk that have a semicolon and a random string appended to the file name.
![image](https://cloud.githubusercontent.com/assets/4435733/23531275/f5096524-ff62-11e6-9ed1-0470229f9dc0.png)

The object_path parameter comes from the pathname field in pulsar.

**Comment by basepi** [comment]
So have we decided these are not real filenames?

**Comment by mew1033** [comment]
I don't know. I would suspect not, but it's certainly possible.

**Comment by basepi** [comment]
This issue was moved to hubblestack/hubble-salt#23
